/*
    Plugin-SDK (Grand Theft Auto San Andreas) header file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk

    Based on definitions from the GTA SA Reversed project.
    https://github.com/gta-reversed/gta-reversed
    Do not delete this comment block. Respect others' work!
*/
#pragma once

enum PLUGIN_API eSoundBankSlot
{
    SND_BANK_SLOT_NONE = -1,
    SND_BANK_SLOT_FRONTEND_GAME = 0,
    SND_BANK_SLOT_FRONTEND_MENU = 1,
    SND_BANK_SLOT_COLLISIONS = 2,
    SND_BANK_SLOT_BULLET_HITS = 3,
    SND_BANK_SLOT_EXPLOSIONS = 4,
    SND_BANK_SLOT_WEAPON_GEN = 5,
    SND_BANK_SLOT_WEATHER = 6,
    SND_BANK_SLOT_DUMMY_ENGINE_0 = 7,
    SND_BANK_SLOT_DUMMY_ENGINE_1 = 8,
    SND_BANK_SLOT_DUMMY_ENGINE_2 = 9,
    SND_BANK_SLOT_DUMMY_ENGINE_3 = 10,
    SND_BANK_SLOT_DUMMY_ENGINE_4 = 11,
    SND_BANK_SLOT_DUMMY_ENGINE_5 = 12,
    SND_BANK_SLOT_DUMMY_ENGINE_6 = 13,
    SND_BANK_SLOT_DUMMY_ENGINE_7 = 14,
    SND_BANK_SLOT_DUMMY_ENGINE_8 = 15,
    SND_BANK_SLOT_DUMMY_ENGINE_9 = 16,
    SND_BANK_SLOT_HORN_AND_SIREN = 17,
    SND_BANK_SLOT_COP_HELI = 18,
    SND_BANK_SLOT_VEHICLE_GEN = 19,
    SND_BANK_SLOT_SPEECH1 = 20,
    SND_BANK_SLOT_SPEECH2 = 21,
    SND_BANK_SLOT_SPEECH3 = 22,
    SND_BANK_SLOT_SPEECH4 = 23,
    SND_BANK_SLOT_SPEECH5 = 24,
    SND_BANK_SLOT_SPEECH6 = 25,
    SND_BANK_SLOT_MISSION1 = 26,
    SND_BANK_SLOT_MISSION2 = 27,
    SND_BANK_SLOT_MISSION3 = 28,
    SND_BANK_SLOT_MISSION4 = 29,
    SND_BANK_SLOT_FOOTSTEPS_PLAYER = 30,
    SND_BANK_SLOT_DOORS = 31,
    SND_BANK_SLOT_SWIMMING = 32,
    SND_BANK_SLOT_SCANNER_INSTRUCTION = 33,
    SND_BANK_SLOT_SCANNER_NUMBER = 34,
    SND_BANK_SLOT_SCANNER_DIRECTION1 = 35,
    SND_BANK_SLOT_SCANNER_DIRECTION2 = 36,
    SND_BANK_SLOT_SCANNER_AREA = 37,
    SND_BANK_SLOT_TEST1 = 38,
    SND_BANK_SLOT_EFFECT1 = 39,
    SND_BANK_SLOT_PLAYER_ENGINE_P = 40,
    SND_BANK_SLOT_FOOTSTEPS_GENERIC = 41,
    SND_BANK_SLOT_BULLET_PASS = 42,
    SND_BANK_SLOT_TEST2 = 43,
    SND_BANK_SLOT_EFFECT2 = 44,
    NUM_SND_BANK_SLOTS = 45
};